apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: ze35wv1qy-python 
  janus-idp.io/tekton: ze35wv1qy-python
  backstage.io/kubernetes-id: ze35wv1qy-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ze35wv1qy-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  