apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: ze35wv1qy-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ze35wv1qy-python 
  name: ze35wv1qy-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: ze35wv1qy-python 
